package com.NEXUS.NEXUS.event;

public enum EventType {

    TASK_ACCEPTED,
    TASK_STARTED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_RETRY_SCHEDULED,
    TASK_DEAD_LETTERED,
    TASK_RECOVERED,
    WORKER_STOPPED,
    WORKER_RESTARTED,
    WORKER_OUT_OF_SERVICE,
    RELEASE_DEPLOYED,
    RELEASE_ROLLED_BACK,
    DEPENDENCY_DEGRADED,
    CACHE_VALIDATED,
    CACHE_DISAGREEMENT,
    OPERATOR_ACTION,
    SYSTEM_ALERT
}
